export ENV_NAME=test
export BRANCH_NAME=master
export REPO=aws-cdk-pipeline-celebrities
export REPO_OWNER=RobertDittmann
export REPO_SECRET_NAME=RobertDittmannGithubToken
cdk deploy AwsCdkPipelineCelebritiesStack
