export ENV_NAME=test
export BRANCH_NAME=add_lambdas_and_stack_with_infrastructure
export REPO=aws-cdk-pipeline-celebrities
export REPO_OWNER=RobertDittmann
export REPO_SECRET_NAME=RobertDittmannGithubToken
cdk deploy AwsCdkPipelineCelebritiesStack
